title: OSMANiC Team Blog
author: Josh @ OSMANiC
description: > # this means to ignore newlines until "baseurl:"
  Official OSMANiC team blog.
# social links
github_username:  OSMANiCTeam # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
plugins:
  - jekyll-feed
